version: 2
jobs:
  build:
    working_directory: ~/marinade
    docker:
      - image: circleci/node:7.10-browsers
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install NPM
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build code
          command: npm run build
  test:
    docker:
      - image: circleci/node:7.10-browsers
    steps:
      - checkout
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit tests with coverage
          command: npm run test-ci
      - run:
          name: Update Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
      - run:
          name: E2E tests
          command: npm run e2e
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
